import type { CMSEvent } from '@/lib/cms'

export const fallbackEvents: CMSEvent[] = [
  {
    id: '1',
    title: 'The Art of Storytelling',
    slug: 'the-art-of-storytelling',
    authorName: 'James Morrison',
    bookTitle: 'Whispers in the Dark',
    bookId: null,
    book: null,
    eventDate: '2026-02-15',
    startTime: null,
    endTime: null,
    duration: null,
    thumbnailUrl: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=800',
    videoUrl: null,
    location: null,
    status: 'scheduled' as const,
    isFeatured: true,
    metadata: null,
    description: 'A deep dive into narrative techniques and the craft of building suspense.',
  },
  {
    id: '2',
    title: 'Southern Gothic Revival',
    slug: 'southern-gothic-revival',
    authorName: 'Eleanor Vance',
    bookTitle: 'Midnight at the Magnolia',
    bookId: 'book-1',
    book: {
      id: 'book-1',
      title: 'Midnight at the Magnolia',
      author: 'Eleanor Vance',
      coverImageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=200',
      purchaseUrl: null,
      genre: 'Fiction',
      description: 'A haunting tale set in the Mississippi Delta.',
    },
    eventDate: '2026-01-18',
    startTime: null,
    endTime: null,
    duration: '1:02:15',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?w=800',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    location: null,
    status: 'recorded' as const,
    isFeatured: false,
    metadata: null,
    description: 'Eleanor Vance joins us to discuss the resurgence of Southern Gothic literature and her latest novel.',
  },
  {
    id: '3',
    title: 'Bourbon & Biographies',
    slug: 'bourbon-and-biographies',
    authorName: 'Marcus Cole',
    bookTitle: 'The Long Road Home',
    bookId: 'book-2',
    book: {
      id: 'book-2',
      title: 'The Long Road Home',
      author: 'Marcus Cole',
      coverImageUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=200',
      purchaseUrl: null,
      genre: 'Biography',
      description: 'A memoir of resilience and reinvention.',
    },
    eventDate: '2026-01-04',
    startTime: null,
    endTime: null,
    duration: '47:30',
    thumbnailUrl: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800',
    videoUrl: 'https://www.youtube.com/watch?v=atljnarLMh4',
    location: null,
    status: 'recorded' as const,
    isFeatured: false,
    metadata: null,
    description: 'Marcus Cole shares the story behind his memoir and the power of personal narrative.',
  },
]
