import type { CMSEvent } from '@/lib/cms'

export const fallbackEvents: CMSEvent[] = [
  // ── Upcoming ──────────────────────────────────────────
  {
    id: 'upcoming-1',
    title: 'The Art of Radical Generosity',
    slug: 'the-art-of-radical-generosity',
    hostName: 'Jessica Schaefer',
    authorName: 'Will Guidara',
    bookTitle: 'Unreasonable Hospitality',
    bookId: 'book-unreasonable',
    book: {
      id: 'book-unreasonable',
      title: 'Unreasonable Hospitality',
      author: 'Will Guidara',
      coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780593418574-L.jpg',
      purchaseUrl: null,
      genre: 'Business',
      description: 'The remarkable power of giving people more than they expect — how the former co-owner of Eleven Madison Park turned a restaurant into the best in the world through obsessive, creative hospitality.',
    },
    eventDate: '2026-02-22',
    startTime: '19:00',
    endTime: '20:30',
    duration: null,
    thumbnailUrl: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=800',
    videoUrl: null,
    location: null,
    status: 'scheduled' as const,
    isFeatured: true,
    metadata: null,
    description: 'Will Guidara joins us to explore the philosophy behind world-class service — and why the most successful leaders, from restaurateurs to CEOs, build empires on the radical idea of giving more than expected. A conversation about client obsession, referral-driven growth, and why hospitality is the ultimate brand strategy.',
  },
  {
    id: 'upcoming-2',
    title: 'What Never Changes',
    slug: 'what-never-changes',
    hostName: 'Christine Park',
    authorName: 'Morgan Housel',
    bookTitle: 'Same as Ever',
    bookId: 'book-same',
    book: {
      id: 'book-same',
      title: 'Same as Ever',
      author: 'Morgan Housel',
      coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780593332702-L.jpg',
      purchaseUrl: null,
      genre: 'Psychology / Business',
      description: 'A guide to what never changes in a world obsessed with what does. Morgan Housel explores the timeless behaviors that drive risk, opportunity, and every decision we make.',
    },
    eventDate: '2026-03-08',
    startTime: '19:00',
    endTime: '20:30',
    duration: null,
    thumbnailUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800',
    videoUrl: null,
    location: null,
    status: 'scheduled' as const,
    isFeatured: false,
    metadata: null,
    description: 'In an era where AI is reshaping every industry overnight, Morgan Housel makes the contrarian case: the most powerful insights come from what stays the same. We explore timeless patterns in human behavior — greed, fear, storytelling, risk — and why understanding them matters more than chasing the next trend.',
  },
  // ── Past Reads ────────────────────────────────────────
  {
    id: 'past-1',
    title: 'Building an Empire from Nothing',
    slug: 'building-an-empire-from-nothing',
    hostName: 'Jessica Schaefer',
    authorName: 'Phil Knight',
    bookTitle: 'Shoe Dog',
    bookId: 'book-shoe-dog',
    book: {
      id: 'book-shoe-dog',
      title: 'Shoe Dog',
      author: 'Phil Knight',
      coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9781501135927-L.jpg',
      purchaseUrl: null,
      genre: 'Memoir / Business',
      description: 'The candid, riveting memoir of the founder of Nike. A story of bootstrapping, near-bankruptcy, and the grit required to build one of the most iconic brands on earth.',
    },
    eventDate: '2026-01-25',
    startTime: '19:00',
    endTime: '20:15',
    duration: '1:12:40',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?w=800',
    videoUrl: 'https://www.youtube.com/watch?v=atljnarLMh4',
    location: null,
    status: 'recorded' as const,
    isFeatured: false,
    metadata: null,
    description: 'We revisited Phil Knight\'s raw, unvarnished account of building Nike from a $50 loan and a handshake deal with a Japanese shoe company. The conversation turned to what every founder knows but rarely says aloud — the loneliness, the cash crunches, and the moments where quitting felt like the rational choice.',
  },
  {
    id: 'past-2',
    title: 'Tactical Empathy in High-Stakes Rooms',
    slug: 'tactical-empathy-in-high-stakes-rooms',
    hostName: 'Andy Duenas',
    authorName: 'Chris Voss',
    bookTitle: 'Never Split the Difference',
    bookId: 'book-never-split',
    book: {
      id: 'book-never-split',
      title: 'Never Split the Difference',
      author: 'Chris Voss',
      coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780062407801-L.jpg',
      purchaseUrl: null,
      genre: 'Negotiation / Psychology',
      description: 'A former FBI hostage negotiator reveals the techniques that work in any negotiation — from boardrooms to billion-dollar deals.',
    },
    eventDate: '2026-01-11',
    startTime: '19:00',
    endTime: '20:20',
    duration: '58:15',
    thumbnailUrl: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    location: null,
    status: 'recorded' as const,
    isFeatured: false,
    metadata: null,
    description: 'Chris Voss walked us through the negotiation frameworks he used to save lives — and how they translate to crisis communications, investor conversations, and closing deals. We explored tactical empathy, calibrated questions, and why the most powerful word in any negotiation is "no."',
  },
  {
    id: 'past-3',
    title: 'When Things Fall Apart',
    slug: 'when-things-fall-apart',
    hostName: 'Jessica Schaefer',
    authorName: 'Ben Horowitz',
    bookTitle: 'The Hard Thing About Hard Things',
    bookId: 'book-hard-thing',
    book: {
      id: 'book-hard-thing',
      title: 'The Hard Thing About Hard Things',
      author: 'Ben Horowitz',
      coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780062273208-L.jpg',
      purchaseUrl: null,
      genre: 'Business / Venture Capital',
      description: 'Ben Horowitz, co-founder of Andreessen Horowitz, offers essential advice on building and running a startup — the hard stuff nobody talks about.',
    },
    eventDate: '2025-12-28',
    startTime: '19:00',
    endTime: '20:30',
    duration: '1:05:22',
    thumbnailUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800',
    videoUrl: 'https://www.youtube.com/watch?v=atljnarLMh4',
    location: null,
    status: 'recorded' as const,
    isFeatured: false,
    metadata: null,
    description: 'We dove into Ben Horowitz\'s unflinching account of the decisions that nearly destroyed his company — and the ones that saved it. From firing friends to managing your own psychology as a CEO, this conversation resonated deeply with anyone who has ever scaled a company and wondered if they were going to make it.',
  },
  {
    id: 'past-4',
    title: 'The Psychology of Money',
    slug: 'the-psychology-of-money',
    hostName: 'Andy Duenas',
    authorName: 'Morgan Housel',
    bookTitle: 'The Psychology of Money',
    bookId: 'book-psych-money',
    book: {
      id: 'book-psych-money',
      title: 'The Psychology of Money',
      author: 'Morgan Housel',
      coverImageUrl: 'https://covers.openlibrary.org/b/isbn/9780857197689-L.jpg',
      purchaseUrl: null,
      genre: 'Finance / Psychology',
      description: 'Timeless lessons on wealth, greed, and happiness — why financial success has less to do with intelligence and more to do with behavior.',
    },
    eventDate: '2025-12-14',
    startTime: '19:00',
    endTime: '20:15',
    duration: '52:30',
    thumbnailUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800',
    videoUrl: 'https://www.youtube.com/watch?v=atljnarLMh4',
    location: null,
    status: 'recorded' as const,
    isFeatured: false,
    metadata: null,
    description: 'Morgan Housel reveals how our relationship with money is shaped by personal history, ego, and emotion — not spreadsheets. A conversation about why financial success has less to do with intelligence and more to do with behavior.',
  },
]
